M48
; DRILL file {KiCad 8.0.3} date 2024-07-02T11:26:58+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-02T11:26:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.400
%
G90
G05
T1
X128.835Y-86.5
X131.375Y-86.5
X149.4Y-86.4
X151.94Y-86.4
T2
X126.8Y-53.8
X154.8Y-53.9
M30
